### ISSUE TITLE
Missing lipids

### ISSUE THREAD

**Issue by mimischi** [Tsjerk/Insane#47]
Happy to see this repository come to life!

I've been wondering for quite some time: why are specific residues, e.g., `POPA` and `DOPA` missing from `insane.py`? Is there any specific reason? Adding them would seem to be a very trivial process.

**Comment by Tsjerk** [comment]
Apologies for the late reply. Yes, it is trivial to add lipids, but for those (and most standard) lipids, they can also be read from the Martini lipid repository, and so it doesn't have priority. This is actually a step towards integrating insane with the Martini/Martinize repositories and functions.

insane -m martini_v2.0_lipids.itp -l POPA -l DOPA -d 10 -o POPA-DOPA.gro

T.
