### ISSUE TITLE
Issue building a membrane with the old lipid topologies

### ISSUE THREAD

**Issue by msidore** [Tsjerk/Insane#51]
Hi,

I've had problems building a membrane with the old lipid topologies (POPG.o, POPE.o, etc.). The command I used to demonstrate it was:
./insane. -x 50 -y 50 -z 15 -o DBol_memb.gro -p DBol.top -pbc rectangular -l POPG.o:200 -l CER.o:800
In this resulting system, the resnames are POPG. (without the o - these atoms are a box of red dots in VMD) and CER.o (with the o this time, this old lipid works even though the resname shouldn't be .o).
Most of the old topologies have the same problems. 

That was using the version from cgmartini.nl - I couldn't use the latest version from github ("global name 'rn' is not defined").

Best regards,
Marlon

**Comment by jbarnoud** [comment]
I just submitted a pull request (PR #52) that fixes the "global name 'rn' is not defined" problem in the newest version. I tried the command line you pasted and the result looked fine with POPG and CER without the `.o`.
