### ISSUE TITLE
Histidine charge error

### ISSUE THREAD

**Issue by biomolsim** [Tsjerk/Insane#70]
Hello everyone,

INSANE is not able to distinguish between the "HIS" and "HIH" histidine residues with a charge of 0 and +1 respectively. Both these residues are defined in Martinize though. This should be rectified soon as it becomes critical while adding the ions.

At the moment, both the residues are assumed to be "HIS" i.e. without charge.

**Comment by Tsjerk** [comment]
Added.

**Comment by biomolsim** [comment]
Thank you, please compile it into the executable file too.
