### ISSUE TITLE
Python 2 scripts not working in Python 3.X

### ISSUE THREAD

**Issue by qinyuz14** [Tsjerk/Insane#74]
Hi Developers,

Thanks for putting together this script for convenience. I would appreciate if you could make switches for some of the functions that have been deprecated in Python 3. The ones that I have noticed include **xrange** and **zip**. I managed to get it work but I would appreciate that if you could push the changes so that I don't have to make them manually. Thank you!

**Comment by Tsjerk** [comment]
The code was recently cleaned up from references to python 2 functionality and python 2 is now not supported anymore (and removed from testing). I saw there's still one reference to xrange, but thats try: range = xrange except NameError: pass, so in python3 it will just stick with python's range. I do note that I did not finalize updating the pypi link. I'll see to that. But the github repo is up-to-date with python3.
