### ISSUE TITLE
Specifying lipid ratio in outer and inner leaflet

### ISSUE THREAD

**Issue by kong1-731** [Tsjerk/Insane#80]
I am just wondering if it is possible to embed a protein in a membrane and to specify the lipid ratio in the outer and inner leaflets separately rather than just the ratio overall in order to design outer and inner leaflets with different lipid compositions. I couldn't find a clear example of this. Thank you for any guidance!

**Comment by Tsjerk** [comment]
This is what insane was designed for from the onset. You can use -l and -u to specify lipids for the lower and upper leaflets, respectively. If only -l is used, then it is interpreted as specifying both leaflets. Examples are given in the original paper.
